/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package myDemoApp;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
        
    public static int[] sortTheArrayBetweenIndexes(int[] array,int firstIndex,int secondIndex,boolean decreasedOrIncrease){//true:decrease,false:increase
        if(firstIndex>secondIndex){
            int temp=firstIndex;
            firstIndex=secondIndex;
            secondIndex=temp; 
        }
        if(firstIndex<0){
            firstIndex=0;
        }
        if(secondIndex>array.length-1){
            secondIndex=array.length-1;
        }
        int key;
        for(int i=firstIndex+1;i<=secondIndex;i++){
            key=array[i];
            int j=i-1;
            if(!decreasedOrIncrease){
                while(j>=firstIndex && array[j]>key){
                    array[j+1]=array[j];
                    j--;
                }
            }
            else{
                while(j>=firstIndex && array[j]<key){
                    array[j+1]=array[j];
                    j--;
                }
            }
            array[j+1]=key;
        } 
        return array;
    }  
    
}
